# Generated by Django 4.2.1 on 2023-08-28 09:24

from django.db import migrations, models


INITIAL_COUNTERS = {
    "audio": 0,
    "video": 0,
    "text": 0,
    "image": 0,
    "file": 0,
    "url": 0,
}


def create_initial_counters(apps, schema_editor):
    RequestCounter = apps.get_model('frequencyapp', 'RequestCounter')
    for data_type, count in INITIAL_COUNTERS.items():
        RequestCounter.objects.create(content_type=data_type, count=count)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=10)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(create_initial_counters),
    ]