# Generated by Django 4.2.1 on 2023-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frequencyapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("json", models.JSONField()),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
