# Generated by Django 4.2.1 on 2023-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frequencyapp", "0002_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="json",
            new_name="request",
        ),
        migrations.AddField(
            model_name="tasks",
            name="file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasks",
            name="response",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
