# Generated by Django 4.2.1 on 2023-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frequencyapp", "0003_rename_json_tasks_request_tasks_file_tasks_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="request",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="response",
            field=models.JSONField(null=True),
        ),
    ]
