# Generated by Django 4.2.1 on 2023-09-12 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("frequencyapp", "0005_rename_tasks_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
