# Generated by Django 4.2.1 on 2023-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frequencyapp", "0008_task_finished"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created",
            new_name="timestamp_created",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="finished",
            new_name="timestamp_finished",
        ),
    ]
