# Generated by Django 5.0.6 on 2024-05-28 22:43

from django.db import migrations

NEW_COUNTER = {
    "unknown": 0,
}

def create_counters(apps, schema_editor):
    RequestCounter = apps.get_model('frequencyapp', 'RequestCounter')
    for data_type, count in NEW_COUNTER.items():
        RequestCounter.objects.create(content_type=data_type, count=count)

class Migration(migrations.Migration):

    dependencies = [
        ('frequencyapp', '0009_rename_created_task_timestamp_created_and_more'),
    ]

    operations = [
        migrations.RunPython(create_counters),
    ]
