#
# using env variables in compose file, see: https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion
#
# in prod we also limit all containers as a group globally to ensure resources remain for ssh access to VM
# see the script to setup docker cgroup in infrastructure folder
#

version: "3"

name: "${COMPOSE_PROJECT_NAME:?You must set compose project name e.g. use the -p flag}"

volumes:
  # volume for this user
  userdata:

networks:
  moonspeaknet:
    external: true
    # will try connecting docker container to already exising network
    name: "${MOONSPEAK_COMPOSE_NETWORK}"

services:
  #==================================
  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    container_name: "u-${COMPOSE_PROJECT_NAME}-s-workelements.moonspeak.${MOONSPEAK_TLD:-localhost}"
    volumes:
      - userdata:/opt/moonspeak/workelements/userdata
    networks:
      - moonspeaknet
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 10M
    environment:
      LOGLEVEL: "INFO"
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
      MOONSPEAK_DEVMODE: ""

  graph:
    depends_on:
      - workelements
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    container_name: "u-${COMPOSE_PROJECT_NAME}-s-graph.moonspeak.${MOONSPEAK_TLD:-localhost}"
    volumes:
      - userdata:/opt/moonspeak/graph/userdata
    networks:
      - moonspeaknet
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 10M
    environment:
      LOGLEVEL: "INFO"
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
      MOONSPEAK_DEVMODE: ""
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="moonspeak.localhost" modified="2023-03-08T09:50:31.755Z" agent="5.0 (X11; Ubuntu)" etag="x1sPpmzUOXcRObYpYGWO" version="20.3.0" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="3702" dy="1137" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="0" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/route/u-${COMPOSE_PROJECT_NAME}-s-workelements/" style="width: 680px; height: 560px; border: medium none;" pointer-events="none" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/router/route/suggestions/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="120" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/router/route/synonyms/" style="width: 474px; height: 424px; border: medium none;" pointer-events="none" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="560" width="490" height="440" as="geometry" />
                  </mxCell>
                </iframe>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="frequency" src="/router/route/frequency/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="6">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="-260" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
