# Also must see the override file: docker-compose.override.yml
#
# This docker-compose is used to run everything with verbose logging for development
#
# Important: you might need to edit /etc/hosts to redirect .moonspeaknet domain to 127.0.0.1
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For interactive pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

volumes:
  # volume to share unix sockets between gateway and router
  unixsocks:
  # volume for demouser1
  userdata:
    name: demouser1_userdata

networks:
  default:
    # the network name is also the alternative top domain for containers e.g. keycloak.moonspeaknet
    # previously used .localhost TLD, but libcurl force resolves it to 127.0.0.1 since version v7.85
    # see: https://serverfault.com/questions/1128965/curl-has-incorrect-dns-resolution-in-a-dind-context
    # but some TLD is needed, because its uses must be located and changed for prod
    name: moonspeaknet

services:
  #===================================
  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    build:
      context: ./moonspeak/gateway
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"
    volumes:
      - unixsocks:/etc/unixsocks
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    build:
      context: ./moonspeak/router
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    env_file:
      - docker-env/router.env

  #===================================
  manager:
    image: "temachpool/moonspeak-manager:${TAG:-latest}"
    build:
      context: ./moonspeak/manager
    ports:
      - "8001:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - docker-env/all.env
      - docker-env/manager.env

  keycloak:
    image: "temachpool/moonspeak-keycloak:${TAG:-latest}"
    build:
      context: ./infra/keycloak
    depends_on:
      # see docker-compose.override.yml
      - postgres
      - mailhog
    command: --verbose start-dev --import-realm
    ports:
      - "8443:8443"
    env_file:
      - docker-env/all.env
      - docker-env/keycloak.env

  landing:
    # no MOONSPEAK_PORT env for landing because nginx is less flexible
    # port 80 gets hardcoded when building the container
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    build:
      context: ./moonspeak/landing
    ports:
      - "8002:80"
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    build:
      context: ./moonspeak/synonyms
    ports:
      - "8043:80"
    env_file:
      - docker-env/synonyms.env

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    build:
      context: ./moonspeak/suggestions
    ports:
      - "8042:80"
    env_file:
      - docker-env/suggestions.env

  frequency:
    image: "temachpool/moonspeak-frequency:${TAG:-latest}"
    build:
      context: ./moonspeak/frequency
    ports:
      - "8005:80"
    env_file:
      - docker-env/frequency.env

  #==================================
  # this is the demo user for development, graph address is the user's unique access url
  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    container_name: u-demouser1-s-workelements.moonspeak.localhost
    build:
      context: ./moonspeak/workelements
    volumes:
      - userdata:/opt/moonspeak/workelements/userdata
    ports:
      - "8040:80"
    env_file:
      - docker-env/workelements.env

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    build:
      context: ./moonspeak/graph
    volumes:
      - userdata:/opt/moonspeak/graph/userdata
    ports:
      - "8041:80"
    container_name: u-demouser1-s-graph
    env_file:
      - docker-env/all.env
      - docker-env/graph.env
    environment:
      # this xml sets default graph value, put here because its multiline
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="moonspeak.localhost" modified="2023-03-08T09:50:31.755Z" agent="5.0 (X11; Ubuntu)" etag="x1sPpmzUOXcRObYpYGWO" version="20.3.0" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="3702" dy="1137" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="0" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/route/u-demouser1-s-workelements/" style="width: 680px; height: 560px; border: medium none;" pointer-events="none" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/router/route/suggestions/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="120" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/router/route/synonyms/" style="width: 474px; height: 424px; border: medium none;" pointer-events="none" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="560" width="490" height="440" as="geometry" />
                  </mxCell>
                </iframe>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="frequency" src="/router/route/frequency/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="6">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="-260" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
