#
# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
# This docker-compose is used to run everything in production setup on .localhost domain
#
# portainer:
#   # See README.md in portainer dir for more info on working with portainer
#   container_name: portainer.moonspeak.localhost
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     # use anon volume during local dev
#     - /data
#   build:
#     context: ./moonspeak/portainer
#
# Important: you might need to define moonspeak.localhost in /etc/hosts 
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

volumes:
  # volume to share unix sockets between gateway and router
  unixsocks:
  # volume for demouser1
  userdata:
    name: demouser1_userdata

networks:
  default:
    # the network name is also the alternative top domain for containers e.g. keycloak.moonspeaknet
    name: moonspeaknet

services:
  #===================================
  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    container_name: gateway
    build:
      context: ./moonspeak/gateway
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"
    volumes:
      - unixsocks:/etc/unixsocks
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    container_name: router
    build:
      context: ./moonspeak/router
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      # dev mode relaxes a number of restrictions (e.g. must have access to gateway's unix socket)
      # also enables self-handling of routes instead of gateway which can be confusing!
      # so do NOT enable this if gateway is enabled, only enable devmode without gateway
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=info"

  #===================================
  manager:
    image: "temachpool/moonspeak-manager:${TAG:-latest}"
    container_name: manager.moonspeak.localhost
    build:
      context: ./moonspeak/manager
    ports:
      - "8001:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TAG: "latest"
      MOONSPEAK_TLD: "localhost"
      MOONSPEAK_DEVMODE: ""
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
      # manager attaches user container to the same default compose network, here we derive this network name
      MOONSPEAK_COMPOSE_NETWORK: "${COMPOSE_PROJECT_NAME}_default"

      # settings for container spin down (container stop & rm)
      MOONSPEAK_SECONDS_BEFORE_IDLE_SPINDOWN: 70
      # must check at least once a minute
      MOONSPEAK_MAX_INTERVAL_DURATION_SECONDS: 30
      # never check more often than once every 10 seconds
      MOONSPEAK_MIN_INTERVAL_DURATION_SECONDS: 10

      # manager will never spin down containers for this user, even after period of inactivity
      MOONSPEAK_IGNORED_DEMO_USER: "demouser1"

      MOONSPEAK_ROOT_SERVICE_NAME: "graph"

      # set debug to on
      PYTHON_ON_WHALES_DEBUG: "1"
      LOGLEVEL: "DEBUG"

  # loki, promtail and grafana stack for logs
  # see: https://mpolinowski.github.io/docs/DevOps/Provisioning/2021-04-07--loki-prometheus-grafana/2021-04-07/
  promtail:
    image: "temachpool/moonspeak-promtail:${TAG:-latest}"
    container_name: promtail.moonspeak.localhost
    build:
      context: ./infra/promtail
    volumes:
      # hopefully we can get rid of docker sock one day and only parse docker logs
      # for now we just disable promtails HTTP server entry point
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MOONSPEAK_LOKI_URL: "http://loki.moonspeak.localhost:3100"
      PROMTAIL_LOG_LEVEL: "error"
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml -print-config-stderr

  # promtail sends log lines to loki, view in grafana
  loki:
    image: "grafana/loki:2.8.2"
    command: -config.file=/etc/loki/local-config.yaml -log.level=error

  jaeger:
    # send tracing data to collector address: https://www.jaegertracing.io/docs/1.46/deployment/#collector
    image: "jaegertracing/all-in-one:latest"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      # LOG_LEVEL: "debug"
    ports:
      - "16686:16686" # jaeger web ui port
      - "4317:4317"   # gRPC otel collector port
      - "4318:4318"   # HTTP otel collector port

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "587:587"
      - "8025:8025"
    environment:
      # use the same smtp port as public services
      MH_SMTP_BIND_ADDR: "0.0.0.0:587"

  postgres:
    image: docker.io/postgres:15.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: "pg_isready -U keycloak -d keycloak"

  keycloak:
    image: "temachpool/moonspeak-keycloak:${TAG:-latest}"
    build:
      context: ./infra/keycloak
    depends_on:
      - postgres
    command: --verbose start-dev --import-realm
    ports:
      - "8443:8443"
    env_file:
      - docker_secrets.env
    environment:
      # KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/certs/server.crt.pem"
      # KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/certs/server.key.pem"
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_LOG_CONSOLE_COLOR: "true"
      KC_LOG_LEVEL: "INFO,io.phasetwo.keycloak:all"
      # plain http port is only used with start-dev
      KC_HTTP_PORT: 8443
      KC_HTTPS_PORT: 8443
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.moonspeaknet:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak 
      # see https://www.keycloak.org/server/hostname
      # keycloak public url, for user browser
      KC_HOSTNAME_URL: "http://localhost:8443"
      # used when importing moonspeak.json realm
      # graph public url, for user browser
      GRAPH_PUBLIC_URL: "http://localhost:8041"
      # GRAPH_CLIENT_SECRET: "graph-client-secret"

  grafana:
    image: "temachpool/moonspeak-grafana:${TAG:-latest}"
    build:
      context: ./infra/grafana
    ports:
      - "3000:3000"
    environment:
      MOONSPEAK_LOKI_URL: "http://loki.moonspeaknet:3100"
      GF_SERVER_DOMAIN: "grafana.moonspeaknet"
      GF_SERVER_ROOT_URL: ""
      GF_SERVER_SERVE_FROM_SUB_PATH: ""
      GF_SERVER_PROTOCOL: "http"
      GF_LOG_LEVEL: "error"
      # allow anonymous user login, see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#anonymous-authentication
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # or login with moonspeak:moonspeak
      # GF_SECURITY_ADMIN_USER: "moonspeak"
      # GF_SECURITY_ADMIN_PASSWORD: "moonspeak"

  landing:
    # no MOONSPEAK_PORT env for landing because nginx is less flexible
    # port 80 gets hardcoded when building the container
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    container_name: landing.moonspeak.localhost
    build:
      context: ./moonspeak/landing
    ports:
      - "8002:80"
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    container_name: synonyms.moonspeak.localhost
    build:
      context: ./moonspeak/synonyms
    ports:
      - "8043:80"
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' "

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    container_name: suggestions.moonspeak.localhost
    build:
      context: ./moonspeak/suggestions
    ports:
      - "8042:80"
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80

  frequency:
    image: "temachpool/moonspeak-frequency:${TAG:-latest}"
    container_name: frequency.moonspeak.localhost
    build:
      context: ./moonspeak/frequency
    ports:
      - "8005:80"
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80

  #==================================
  # this is the demo user for development,  graph address is the user's unique access url
  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    container_name: u-demouser1-s-workelements.moonspeak.localhost
    build:
      context: ./moonspeak/workelements
    volumes:
      - userdata:/opt/moonspeak/workelements/userdata
    environment:
      LOGLEVEL: "INFO"
      MOONSPEAK_DEVMODE: ""
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
    ports:
      - "8040:80"

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    # prioritise graph startup time over unlikely race condition, so drop depends_on
    # depends_on:
    #   - workelements
    build:
      context: ./moonspeak/graph
    volumes:
      - userdata:/opt/moonspeak/graph/userdata
    ports:
      - "8041:80"
    container_name: u-demouser1-s-graph
    env_file:
      - docker_secrets.env
    environment:
      MOONSPEAK_USER: "demouser1"
      MOONSPEAK_KEYCLOAK_BACKEND_URL: "http://keycloak.moonspeaknet:8443"
      LOGLEVEL: "INFO"
      MOONSPEAK_OIDC_CRYPTO_PASSPHRASE: "long-random-passphrase-to-secure-apache-mod-oidc-cookies"
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="moonspeak.localhost" modified="2023-03-08T09:50:31.755Z" agent="5.0 (X11; Ubuntu)" etag="x1sPpmzUOXcRObYpYGWO" version="20.3.0" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="3702" dy="1137" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="0" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/route/u-demouser1-s-workelements/" style="width: 680px; height: 560px; border: medium none;" pointer-events="none" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/router/route/suggestions/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="120" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/router/route/synonyms/" style="width: 474px; height: 424px; border: medium none;" pointer-events="none" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="560" width="490" height="440" as="geometry" />
                  </mxCell>
                </iframe>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="frequency" src="/router/route/frequency/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="6">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="-260" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
