# Must set serverName before including anything
Define serverName graph-${MOONSPEAK_USER}

# apache ifdefine hack: https://serverfault.com/questions/1022233/using-ifdefine-with-environment-variables
Define "MOONSPEAK_PLATFORM_${MOONSPEAK_PLATFORM}"
Define "MOONSPEAK_DISABLE_AUTH_${MOONSPEAK_DISABLE_AUTH}"

<IfDefine MOONSPEAK_PLATFORM_mac>
# config used when running without docker (brew install apache2), relies on serverName to be set
Include ${PWD}/../../apache_mac.conf
Listen 8041
</IfDefine>

<IfDefine MOONSPEAK_PLATFORM_docker>
# the config relies on serverName to be set
Include /opt/moonspeak/apache_docker.conf
</IfDefine>


<IfDefine MOONSPEAK_DISABLE_AUTH_0>
# to test this error page, set invalid client credentials OIDCClientSecret, then it will appear every time
OIDCHTMLErrorTemplate "../frontend/apache_oidc_html_error_template.html"
</IfDefine>

# for graph we do not use URL redirects to specific language e.g. /en/ or /ru/
# so just disable the rewrite engine
RewriteEngine Off

DocumentRoot "../frontend/src/main/webapp"
<Directory "../frontend/src/main/webapp">
    Require all granted
</Directory>

Alias "/config" "../config"
<Directory "../config">
    Require all granted
</Directory>

WSGIScriptAlias "/api/" "apache.wsgi/api/"
<Files "./apache.wsgi">
    Require all granted
</Files>
