version: "3"

volumes:
  # volume to share unix sockets between gateway and router
  unixsocks:
    # specify name to avoid default docker-compose prefixing
    name: unixsocks

networks:
  # global network to share between all services
  moonspeaknet:
    # specify name to avoid default docker-compose prefixing
    # because manager must bring up containers on the exact same network
    name: moonspeaknet

services:
  #===================================
  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks
    networks:
      - moonspeaknet

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    networks:
      - moonspeaknet
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name, the field is re-defined in override configs
      MOONSPEAK_DOMAIN: ""
      # turn off debug features
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=info"

  manager:
    image: "temachpool/moonspeak-manager:${TAG:-latest}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
      # the manager writes configuration for graph service which has absolute urls
      # this supplies the correct name, the field is re-defined in override configs
      MOONSPEAK_TLD: ""
      # set debug to off
      PYTHON_ON_WHALES_DEBUG: ""
      LOGLEVEL: "INFO"
      MOONSPEAK_DEVMODE: ""

  #===================================
  # by default do not run grafana and loki, only promtail
  promtail:
    container_name: promtail.moonspeak.localhost
    image: "temachpool/moonspeak-promtail:${TAG:-latest}"
    volumes:
      # hopefully we can get rid of docker sock one day and only parse docker logs
      # for now we just disable promtails HTTP server entry point
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moonspeaknet
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml -print-config-stderr

  landing:
    # no MOONSPEAK_PORT env for landing because nginx is less flexible
    # port 80 gets hardcoded when building the container
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    networks:
      - moonspeaknet

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    networks:
      - moonspeaknet
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' "

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80

  frequency:
    image: "temachpool/moonspeak-frequency:${TAG:-latest}"
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80
