# Generated by Django 4.0 on 2022-01-15 19:03

from django.db import migrations, models
import json
from pprint import pprint


def default_values(apps, schema_editor):
    with open("../resources/radicals.json") as radicals:
        data = json.load(radicals)

    Radical = apps.get_model('breakdown', 'Radical')

    for element in data.values():
        radical = Radical(**element)
        radical.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('kanji', models.CharField(max_length=200)),
                ('unicode', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('svg', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RunPython(default_values),
    ]
