# Generated by Django 4.0 on 2022-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicals', models.CharField(max_length=10000)),
                ('keyword', models.CharField(max_length=200)),
                ('kanji', models.CharField(max_length=200)),
                ('unicode', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('svg', models.CharField(max_length=10000)),
            ],
        ),
    ]
